jobs:
  - name: print-hello-2
    plan:
      - task: hello
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: alpine }
          run:
            path: sh
            args:
              - -c
              - echo "Olá do pipeline template do GitHub!"
