jobs:
  - name: print-hello
    plan:
      - task: hello
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: alpine }
          run:
            path: sh
            args:
              - -exc
              - |
                echo "Iniciando deploy 2"
                exit 1  # Simula falha
